### ISSUE TITLE
Daten werden nicht mehr Synchronisiert

### ISSUE THREAD

**Issue by marcohanke** [gharlan/redaxo_developer#26]
Erstmal danke für das extrem hilfreiche Addon, ich nutze es nur noch und bin im Prinzip zufrieden.
Heute Habe ich auf meinem Server eine neue Redaxo Instanz installiert. Danach wie immer Seo42 und Developer aktiviert. Leider werden meine Templates nach dem ändern nicht mahr aktualisiert.
Ich habe schon alles probiert, Addon neu installiert, Cache gelöscht, Redaxo Setup neu durchgeführt. Ich muss nach jeder Änderung das Template öffnen und auf übernehmen klicken, oder den Cache löschen.
Liegt es evtl. an einer neuen Redaxo Version ???

**Comment by gharlan** [comment]
Sorry für die sehr späte Reaktion. Irgendwie hatte ich hier die Issues gar nicht auf dem Schirm.
Konntest du das Problem lösen?

**Comment by marcohanke** [comment]
Ich hab’ es nicht zu 100% verfolgt,
aber es scheint zu funktionieren, wenn ich im Backend angemeldet bin und NICHT zu funktionieren, wenn ich NICHT angemeldet bin.


Beste Grüße 
Marco

--------------------------------------------------





Marco Hanke | 36 Pixel
Sigildisstraße 44a | 36167 Nüsttal

E-Mail: marco@36pixel.de <mailto:marco@36pixel.de>
Telefon: 0 66 52 / 79 63 0 - 68

Ust-IdNr.: DE251672618  

--------------------------------------------------

**Comment by gharlan** [comment]
Achso, das ist das Prinzip des Addons. Es wird nur synchronisiert, wenn man als Backend als Admin eingeloggt ist. Dann aber auch beim Frontend-Aufruf.
Grund: Der Overhead wäre sonst bei den normalen Seitenaufrufen zu groß.

**Comment by marcohanke** [comment]
OK, kapiert. ;-)
Hatte ich nur nirgends gelesen (wobei ich es evtl. auch überlesen habe).


Beste Grüße 
Marco

--------------------------------------------------





Marco Hanke | 36 Pixel
Sigildisstraße 44a | 36167 Nüsttal

E-Mail: marco@36pixel.de <mailto:marco@36pixel.de>
Telefon: 0 66 52 / 79 63 0 - 68

Ust-IdNr.: DE251672618  

--------------------------------------------------

**Comment by gharlan** [comment]
Es steht in der Readme. ;)
Aber du bist nicht der erste, der darüber gestolpert ist, daher werde ich mal schauen, wie ich es noch deutlicher machen kann.
