### ISSUE TITLE
Synchronisation in einen Ordner außerhalb von redaxo/include

### ISSUE THREAD

**Issue by DanielWeitenauer** [gharlan/redaxo_developer#27]
Hi Gregor,

es wäre cool, wenn es die Möglichkeit gäbe, die Synchronisationsdateien außerhalb des redaxo/include Ordners anzulegen. Viele legen für ihre Redaxo-Installationen einen eigenen Assets-Ordner an, der auf oberster ebene neben den Systemordnern liegt. Wenn da dann auch die Template und Modul-Daten hineinsynchronisiert werden könnten, hätte man Frontend-technisch alles an einem Ort.

**Comment by gharlan** [comment]
Siehe #6.

**Comment by DanielWeitenauer** [comment]
Ah, ok, dann hat sich das hier ja schon erledigt. Danke!
