### ISSUE TITLE
500 Server Error mit php5-fpm/FastCGI

### ISSUE THREAD

**Issue by tzfrs** [gharlan/redaxo_developer#29]
Hallo,

ich habe dieses Addon problemlos auf meinen alten Servern genutzt, aber wenn ich das bei Servern mit php-fpm nutze, dann kommt - wenn das Addon synchronisiert - ein 500er Server Error mit folgedendem Fehler:

    [Tue Nov 10 11:32:59 2015] [error] [client xx.xx.xx.xx] (104)Connection reset by peer: FastCGI: comm with server "/fcgi-bin-php5-fpm-example" aborted: read failed, referer: http://example.com/redaxo/
    [Tue Nov 10 11:32:59 2015] [error] [client xx.xx.xx.xx] FastCGI: incomplete headers (0 bytes) received from server "/fcgi-bin-php5-fpm-example", referer: http://example.com/redaxo/

Danach aktualisier ich die Seite noch einmal und es geht problemlos. Woran kann denn so etwas liegen?Server-Administrator nimmt an, dass es ein Problem mit dem Addon ist, dass es nicht richtig mit php5-fpm funktioniert.

**Comment by gharlan** [comment]
Sorry für die späte Reaktion. Irgendwie hatte ich hier die Issues gar nicht auf dem Schirm.
Bist du irgendwie weiter gekommen mit dem Problem?

**Comment by gharlan** [comment]
Ich schließe mal. Falls noch aktuell, bitte hier nochmal melden.
