### ISSUE TITLE
Webdav support: module/templates/...

### ISSUE THREAD

**Issue by staabm** [gharlan/redaxo_developer#30]
Anstatt die ganzen inhalte auf die platte zu replizieren, was vorraussetzt dass der user einen ftp/ssh zugang zum system hat wäre es scharmanter die inhalte via webdav zu publishen und die rechte der user zu berücksichtigen, d.h. Jeder sieht nur wo er rechte drauf hat.

Man könnte das ganze noch weiter treiben und sogar inhalte von seiten pflegbar machen in dieser manier...Dann wäre es aber vermutlich ein neues webdav-addon

**Comment by gharlan** [comment]
Ich finde den Ansatz zwar interessant, werde es aber nicht umsetzen.
Hauptgrund: Ich möchte, dass die Templates/Module gemeinsam mit dem Code versionisierbar sind. Auch sollen sie gemeinsam über FTP austauschbar sein, zwischen lokal und Server.
