### ISSUE TITLE
Automatisches anlegen in die DB scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by tbaddade** [gharlan/redaxo_developer#31]
> Es können neue Items über das Dateisystem angelegt werden. Dazu genügt es einen neuen Ordner anzulegen mit mindestens einer der aufgelisteten Dateien.

Ich habe einen Template Ordner vom Server gezogen. Das Template wurde nicht angelegt. Ganz im Gegenteil, der Ordner wurde automatisch wieder gelöscht.

**Comment by gharlan** [comment]
Ich hab mir das mal angeschaut, wann genau die Ordner gelöscht werden.

Du müsstest die Datei `.rex_id_list` in den verschiedenen Sync-Ordnern in deinem Deployment auf Exclude setzen. Denn die liefert Developer genau die Information, welche IDs es bei der letzten Synchronisation schon gab. Und wenn du die jetzt mit downloadest, enthält sie die Informationen des Servers statt die korrekten deiner lokalen Installation.

Ich muss mal schauen, ob/wie ich das verbessern kann.

**Comment by gharlan** [comment]
Ich denke, ich werde `.rex_id_list` entfernen, und die Information stattdessen in der rex_config und somit in der DB speichern. Gerade, weil die Information nun mal fest zur aktuellen Installation gehört.
