### ISSUE TITLE
Compser Autoload Problem

### ISSUE THREAD

**Issue by NGWNGW** [gharlan/redaxo_developer#32]
Hallo Gregor, 

ich habe folgendes Problem (Redaxo 4 Version) festgestellt:

Wenn ein anderes Projekt auch Composer nutzt und nach dem Developer-Addon geladen wird führt es zu einem "Fatal Error". Ursache ist dass das developer Addon für REX4 einen relativ alten Autoloader von Composer nutzt der mit den neuen nicht mehr kompatibel ist.

Abhilfe sollte ein "dump-autoload" mit einer neuen Composer-Version schaffen.

Gruß
Nico

**Comment by gharlan** [comment]
Ja, leider ein nerviges Problem. An der gleichen Stelle war ich auch schon mal, nur umgekehrt. Damals hatte developer eine neuere Composer-Autoloader-Version als ein anderen Addon.

Habe #28 gemerged.
