### ISSUE TITLE
Zustand für "Module synchronisieren" in Einstellungen wird nicht gespeichert.

### ISSUE THREAD

**Issue by chip75** [gharlan/redaxo_developer#33]
Checkbox behält immer vorherigen Status

**Comment by sbrinkers** [comment]
kann ich bestätigen...
in der pages/index.php steht bei $this->setConfig "module" statt "module**s**",
nach Korrektur dort und in der Datenbank und einem reinstall, gings dann bei mir...

**Comment by staabm** [comment]
@sbrinkers möchtest du ein PR beisteuern?
