### ISSUE TITLE
Nach Umzug der Seite Fehlermeldung in den Logs:

### ISSUE THREAD

**Issue by olien** [gharlan/redaxo_developer#34]
> 19.05.2016 10:16:06	Warning	touch(): Utime failed: Die Operation ist nicht erlaubt	
> redaxo/src/addons/developer/lib/synchronizer.php  154

Dateirechte?

**Comment by staabm** [comment]
Ja.

**Comment by gharlan** [comment]
Danke für's Melden, ich schließe hier aber, da ich hier nicht viel machen kann..
